query getTrip($tripId: ID!) {
  node(id: $tripId) {
    id
    __typename
    ... on Trip {
      createdAt
      name
      description
      admin {
        id
        displayName
        username
      }
      members {
        role
        color
        user {
          id
          displayName
          username
        }
      }
      itinerary {
        id
        latitude
        longitude
        name
        description
        previousTripRoutePoint {
          name
        }
        nextTripRoutePoint {
          name
        }
        activities {
          id
          routePoint {
            id
            name
          }
          name
          description
          addedByUser {
            id
            username
            displayName
          }
          startDate
          endDate
          activityReactions {
            id
            activityReactionType
            addedByUser {
              id
            }
          }
        }
      }
    }
  }
}
