name: Continuous Deployment

on: [pull_request]

jobs:
  expo-publish:
    name: Publish pull request on Expo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Setup Expo
        uses: expo/expo-github-action@7.0.3
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true

      - name: Install dependencies
        run: yarn install

      - name: Publish pull request on Expo
        run: expo publish --release-channel=pr-${{ github.event.number }}

      - name: Comment when ready
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: App is ready for review, you can [see it here](https://expo.io/@${{ secrets.EXPO_CLI_USERNAME }}/${{ secrets.EXPO_CLI_USERNAME }}?release-channel=pr-${{ github.event.number }}).
