
name: Continuous Integration

on: [push, pull_request]

jobs:
  coding-guidelines:
    name: Build Project

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install
